# -*- coding: utf-8 -*-
"""Student Record Management System.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1roKy4RpIPZk93fP4vZYfMkNmDaX-EiK8
"""

import csv
import os

FILE_NAME = "students.csv"

if not os.path.exists(FILE_NAME):
    with open(FILE_NAME, "w", newline="") as file:
        writer = csv.writer(file)
        writer.writerow(["ID", "Name", "Age", "Branch"])

print("Student database is ready!")

def add_student():
    try:
        student_id = input("Enter Student ID: ")
        name = input("Enter Student Name: ")
        age = int(input("Enter Student Age: "))
        branch = input("Enter Student Branch: ")

        with open(FILE_NAME, "a", newline="") as file:
            writer = csv.writer(file)
            writer.writerow([student_id, name, age, branch])

        print("Student added successfully!")

    except ValueError:
        print("Age must be a number!")

    except Exception as e:
        print("An error occurred:", e)

add_student()

def view_student():
    with open(FILE_NAME, "r", newline="") as file:
        reader = csv.reader(file)

        print("\n{:<10} {:<15} {:<10} {:<10}".format(
            "ID", "Name", "Age", "Branch"
        ))
        print("-" * 45)

        next(reader)

        for row in reader:
            print("{:<10} {:<15} {:<10} {:<10}".format(
                row[0], row[1], row[2], row[3]
            ))

view_student()

def update_student():
    student_id = input("Enter Student ID to update: ")

    students = []

    with open(FILE_NAME, "r", newline="") as file:
        reader = csv.reader(file)
        header = next(reader)

        for row in reader:
            if row[0] == student_id:
                print("Student found!")

                name = input("Enter new name: ")
                age = input("Enter new age: ")
                branch = input("Enter new branch: ")

                row = [student_id, name, age, branch]

            students.append(row)

    with open(FILE_NAME, "w", newline="") as file:
        writer = csv.writer(file)
        writer.writerow(header)
        writer.writerows(students)

    print("Student updated successfully!")

update_student()

def delete_student():
    student_id = input("Enter Student ID to delete: ")

    students = []
    found = False

    with open(FILE_NAME, "r", newline="") as file:
        reader = csv.reader(file)
        header = next(reader)

        for row in reader:
            if row[0] == student_id:
                found = True
            else:
                students.append(row)

    with open(FILE_NAME, "w", newline="") as file:
        writer = csv.writer(file)
        writer.writerow(header)
        writer.writerows(students)

    if found:
        print("Student deleted successfully!")
    else:
        print("Student ID not found!")

delete_student()

try:
    age = int(input("Enter student age: "))
    print("Age:", age)

except ValueError:
    print("Please enter a valid number!")

try:
    age = int(input("Enter student age: "))
    print("Age:", age)

except ValueError:
    print("Invalid age!")

finally:
    print("Program execution completed.")

while True:

    print("\n=================================")
    print(" STUDENT RECORD MANAGEMENT SYSTEM")
    print("=================================")

    print("1. Add Student")
    print("2. View Students")
    print("3. Update Student")
    print("4. Delete Student")
    print("5. Exit")

    choice = input("Enter your choice: ")

    if choice == "1":
        add_student()

    elif choice == "2":
        view_student()

    elif choice == "3":
        update_student()

    elif choice == "4":
        delete_student()

    elif choice == "5":
        print("Thank you for using the system!")
        break

    else:
        print("Invalid choice! Please enter 1 to 5.")